### PR TITLE
Fixed profile image upload (creates directory if not exist)

### PR DESCRIPTION
**Pull request by kenfehling**

### CODE REVIEW

**Comment by pgeiss** [comment]
Unless `mkdirp` is in keystone already, add it to the `package.json` please. If we don't, `npm install` won't work properly.

**Comment by kenfehling** [comment]
OK added

**Comment by pgeiss** [comment]
package.son haha, looks good now though

**Comment by kenfehling** [comment]
OK, fixed the merge conflicts

**Pull request merged**
